### ISSUE TITLE
Odd number of TC members

### ISSUE THREAD

**Issue by oesteban** [github/MVG#10]

**Comment by hyandell** [comment]
This feels like useful information for an expanded "How to get started". Currently the README is pretty terse there, it's the what to do rather than any philosophy and thinking.  Perhaps a subsequent document gets more into:  "How to grow your organization..."

* Deciding whether you want the Steering Committee to be a Board or Most Maintainers
* Boards should have odd numbers of members when possible
etc

**Comment by oesteban** [comment]
@hyandell, thanks for commenting on this. I apologize because this issue without description was meant for a forked project where we are basing the governance documents on the MVG and I accidentally posted it here. Nonetheless, I'm glad you are actioning this misplace thought - thanks much.
